import { type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { api } from "../utils/api";
import "../styles/globals.css";
import Head from "next/head";
import SessionWrapper from "../components/wrappers/SessionWrapper";
import Notification from "../components/Notification/Notification";
import AppWrapper from "../components/Layout/AppWrapper";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Fitness Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SessionWrapper>
        <Notification>
          <AppWrapper>
            <Component {...pageProps} />
          </AppWrapper>
        </Notification>
      </SessionWrapper>
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
